# Root logger configuration
rootLogger.level = DEBUG
rootLogger.appenderRef.stdout.ref = STDOUT
rootLogger.appenderRef.file.ref = LOGFILE

# Console appender configuration
appender.console.name = STDOUT
appender.console.type = Console
appender.console.layout.type = PatternLayout
appender.console.layout.pattern = CustomLogger: [%-5level] %d{yyyy-MM-dd HH:mm:ss.SSS} [%t] %c{1} - %msg%n


# to file
appender.file.type = File
appender.file.name = LOGFILE
appender.file.fileName = /Users/cml/dev/code/game-zscore/api_logs/log-tester.log
appender.file.layout.type = PatternLayout
appender.file.layout.pattern = CustomLogger: [%-5level] %d{yyyy-MM-dd HH:mm:ss.SSS} [%t] %c{1} - %msg%n