# properties
property.LOG_DIR = /Users/cml/dev/code/game-zscore/api_logs/

# Root logger configuration
rootLogger.level = INFO
rootLogger.appenderRef.stdout.ref = STDOUT

# custom class logger
logger.customLogger.name = customClassLogger
logger.customLogger.level = debug
logger.customLogger.appenderRef.customFile.ref = CustomFileAppender
logger.customLogger.additivity = false

# Console appender configuration
appender.console.name = STDOUT
appender.console.type = Console
appender.console.layout.type = PatternLayout
appender.console.layout.pattern = CustomLogger: [%-5level] %d{yyyy-MM-dd HH:mm:ss.SSS} [%t] %c{1} - %msg%n

# to file, custom classes only
appender.customFile.type = File
appender.customFile.name = CustomFileAppender
appender.customFile.fileName = ${LOG_DIR}/zscore-api-custom.log
appender.customFile.layout.type = PatternLayout
appender.customFile.layout.pattern = CustomLogger: [%-5level] %d{yyyy-MM-dd HH:mm:ss.SSS} [%t] %c{1} - %msg%n